


- job-template:
    name: 'pi-gen'
    project-type: pipeline
    sandbox: false
    disabled: false
    concurrent: false
    properties:
      - build-discarder:
          num-to-keep: 3
      - rebuild:
          auto-rebuild: true
          rebuild-disabled: false
      - raw:
          xml: |
            <org.jenkinsci.plugins.workflow.job.properties.DisableResumeJobProperty/>
    description: |-
        Build for https://github.com/elo-enterprises/pi-gen/
    parameters:
      - string:
          name: BRANCH
          description: Branch to use
          default: master
      - string:
          name: REPO
          description: Repo to use
          default: 'git@github.com:elo-enterprises/pi-gen.git'
          # default: https://github.com/elo-enterprises/pi-gen.git
    dsl: |
      // library identifier: "jenkins-libs", changelog: false
      pipeline {{
      agent any;  stages {{
        stage("INIT") {{ steps{{ script {{
            step([$class: 'WsCleanup']);
              checkout([
                $class: 'GitSCM',
                branches: [[name: "${{params.BRANCH}}"]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [
                  [ $class: 'RelativeTargetDirectory',
                    relativeTargetDir: "." ],
                  [ $class: 'SubmoduleOption',
                    disableSubmodules: false,
                    parentCredentials: false,
                    recursiveSubmodules: true,
                    reference: '',
                    trackingSubmodules: false ] ],
                submoduleCfg: [],
                userRemoteConfigs: [[
                  url: "${{params.REPO}}",
                  // NB: uncomment/configure if your github ssh keys are not
                  // setup & you prefer to use the jenkins credentials database
                  //credentialsId: "github",
                ] ],
              ]);
        }} }} }} // script // steps // stage
        stage("Toggle") {{
          steps {{ ansiColor('xterm') {{
            sshagent([]) {{
              sh("""
              make clean configure
              make build
              """)
            }}
        }} }} }} // ansiColor // steps // stage
      }} }} // stages // pipeline
    # triggers:
    #   - pollscm:
    #       cron: "H/2 * * * *"
    #       ignore-post-commit-hooks: True
    # pipeline-scm:
    #   scm:
    #     - git:
    #         url: "{repo}"
    #         refspec: +refs/heads/*:refs/remotes/origin/*
    #         credentials-id: "{default}"
    #         branches: ['origin/**']
- project:
    name: pi-gen-project
    jobs: ['pi-gen']
